import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:postreq_flutter/api_const.dart';
import 'package:toast/toast.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'common_res_model.dart';
import 'loginnotreq.dart';

class Home extends StatefulWidget {
  late Autogenerated autos;

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late Autogenerated autos;

  TextEditingController nameCtrl = TextEditingController();
  TextEditingController ageCtrl = TextEditingController();
  TextEditingController salaryCtrl = TextEditingController();

  @override
  void initState() {
    super.initState();
  }

  Future getcvalueEmail() async {
    final SharedPreferences share = await SharedPreferences.getInstance();
    share.setBool('isLogin', true);
  }

  Future<void> onCreate() async {
    if (isValid()) {
      print('Form is okay');

      final dynamic data = <String, dynamic>{
        'name': nameCtrl.text.trim(),
        'salary': salaryCtrl.text.trim(),
        'age': ageCtrl.text.trim()
      };

      var url = Uri.parse(Api.baseUrl + Api.create);
      var responce = await http.post(url, body: data);
      Map<String, dynamic> decodejson = json.decode(responce.body);
      Autogenerated auto = Autogenerated.fromJson(decodejson);

      setState(() {
        autos = auto;
      });
      if (auto.status == 'success') {
        getcvalueEmail();
        Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => Logno()),
        );
        Toast.show("Sucess", context);
      } else {
        Toast.show("Failed", context);
      }

      print(responce.statusCode);
      print(responce.body);
    }
  }

  bool isValid() {
    if (nameCtrl.text.isEmpty) {
      Toast.show("enter name", context,
          duration: Toast.LENGTH_LONG, gravity: Toast.BOTTOM);
      print('pk');

      return false;
    } else if (salaryCtrl.text.isEmpty) {
      Toast.show("Enter salary", context,
          duration: Toast.LENGTH_LONG, gravity: Toast.BOTTOM);
      return false;
    } else if (ageCtrl.text.isEmpty) {
      Toast.show("Enter age", context,
          duration: Toast.LENGTH_LONG, gravity: Toast.BOTTOM);
      return false;
    }
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('API_Post'),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(15.0),
            child: TextFormField(
              controller: nameCtrl,
              decoration: const InputDecoration(
                  labelText: 'Name',
                  hintText: 'Enter Your Name',
                  prefixIcon: Icon(
                    Icons.supervised_user_circle_sharp,
                    color: Colors.redAccent,
                  )),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(15.0),
            child: TextFormField(
              controller: salaryCtrl,
              decoration: const InputDecoration(
                  labelText: 'Salary detail',
                  hintText: 'Enter Your Salary',
                  prefixIcon: Icon(
                    Icons.supervised_user_circle_sharp,
                    color: Colors.blueAccent,
                  )),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(15.0),
            child: TextFormField(
              controller: ageCtrl,
              decoration: const InputDecoration(
                  labelText: 'Age',
                  hintText: 'Enter Your Age',
                  prefixIcon: Icon(
                    Icons.supervised_user_circle_sharp,
                    color: Colors.green,
                  )),
            ),
          ),
          const SizedBox(
            height: 20,
          ),
          ElevatedButton(onPressed: onCreate, child: Text('Submit'))
        ],
      ),
    );
  }
}
